### ISSUE TITLE
Не работает приложение

### ISSUE THREAD

**Issue by llean2k** [Garneg/SerbianDictionary#1]
Помогите! Не работает речник этот ваш, переехал в Белград, пошел в магазин, хотел купить похавать и открыл ваш словарь, а там открывается вебвью с казиком, проиграл квартиру.
![yjjU7p2iqF0](https://github.com/Garneg/SerbianDictionary/assets/124933877/e05994d3-f7c5-4920-9b64-21b3fdbed2cb)

**Comment by ershovstanislav620** [comment]
Да  не пизди еблан, я выиграл, топовый казик

**Comment by Garneg** [comment]
Ладно, братан, тебе пора обратно
![](https://files.hotmc.ru/upload/it/u2g657n4xkim46tosf2udfwuffy5fqtyhjgyab8wz29qal4xd6cyq9uuy8m21m5p.jpg?1657032122)
